version: 1 
builder:   
  configs:
  - documentation_targets: [WrkstrmColor]
    custom_documentation_parameters: [--include-extended-types]
  - platform: watchos
    scheme: ComposableArchitecture_watchOS
    swift_version: '5.9'
  - platform: ios
    swift_version: '5.9'
  - platform: macos
    swift_version: '5.9'
  - platform: ipados
    swift_version: '5.9'
  - platform: linux
    swift_version: '5.9'
    image: registry.gitlab.com/finestructure/spi-images:AppKid-5.8-latest
