name: "\U0001F9F9 Swift Lint| WrkstrmColor"
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    paths:
    - '**'
jobs:
  swift-build:
    strategy:
      matrix:
        os:
        - macos-13
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Cache Homebrew dependencies
      id: cache-brew
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-homebrew-${{ hashFiles('**/Brewfile') }
        path: /usr/local/Homebrew ~/Library/Caches/Homebrew
    - name: Check Cache
      run: 'echo ''Cache hit: ${{ steps.cache-brew.outputs.cache-hit }}'''
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-13' || matrix.os == 'self-hosted'
      with:
        xcode-version: '15.0'
    - name: Set CI Style
      run: echo "SPM_CI_USE_LOCAL_DEPS=false" >> $GITHUB_ENV
    - name: Check CI Style
      run: '[ -z "${SPM_CI_USE_LOCAL_DEPS}" ] && echo "SPM_CI_LOCAL_DEPS is not set"
        || echo "SPM_CI_USE_LOCAL_DEPS is set to ${SPM_CI_USE_LOCAL_DEPS}"'
      env:
        SPM_CI_USE_LOCAL_DEPS: ${{ env.SPM_CI_USE_LOCAL_DEPS }}
    - name: Swift SWIFTLINT
      if: steps.cache-brew.outputs.cache-hit != 'true'
      run: brew install swiftlint
    - name: SwiftLint
      run: swiftlint
